//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaHussainWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basics()
        {
            this.ImageBackground = new HashSet<ImageBackground>();
        }
    
        public int BasicID { get; set; }
        public string email { get; set; }
        public string Address { get; set; }
        public string website { get; set; }
        public string ourServtxt { get; set; }
        public string headerMidtxt { get; set; }
        public string ParagMidtxt { get; set; }
        public string callus { get; set; }
        public string maintextNews { get; set; }
        public string mainImagText1 { get; set; }
        public string mainImagText2 { get; set; }
        public string parImgtxt { get; set; }
        public string midHeaderIndexPage { get; set; }
        public string midParaIndexPage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageBackground> ImageBackground { get; set; }
    }
}
