//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaHussainWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branches()
        {
            this.BranchDetail = new HashSet<BranchDetail>();
        }
    
        public int BID { get; set; }
        public string phone { get; set; }
        public string Title { get; set; }
        public string mainImg { get; set; }
        public string AddBranche { get; set; }
        public string enTitle { get; set; }
        public string enAddrBranch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchDetail> BranchDetail { get; set; }
    }
}
