//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaHussainWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imgNew
    {
        public int NewID { get; set; }
        public string img { get; set; }
        public string Headertxt { get; set; }
        public Nullable<System.DateTime> DateNew { get; set; }
        public string Maintxt { get; set; }
        public string enHeadertxt { get; set; }
        public string enMaintxt { get; set; }
    }
}
