//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbaHussainWebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class maindbEntities2 : DbContext
    {
        public maindbEntities2()
            : base("name=maindbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basics> Basics { get; set; }
        public virtual DbSet<BranchDetail> BranchDetail { get; set; }
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<ImageBackground> ImageBackground { get; set; }
        public virtual DbSet<imgNew> imgNew { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<setting> setting { get; set; }
        public virtual DbSet<SocialMedia> SocialMedia { get; set; }
        public virtual DbSet<SubCategory> SubCategory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
